config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  match '/infravisor',            to: 'infra_visor#index',     via: 'get'
  match '/infravisor/download',   to: 'infra_visor#download',  via: 'get'

  match '/voicemessages',         to: 'voice_message#index',   via: 'get'
  match '/voicemessages/download',to: 'voice_message#download',via: 'get'

  match '/callforwarder',         to: 'call_forwarder#index',  via: 'get'
  match '/callforwarder/update',  to: 'call_forwarder#update', via: 'post'

  match '/signin',                to: 'sessions#new',          via: 'get'
  match '/signin',                to: 'sessions#create',       via: 'post'
  match '/signout',               to: 'sessions#destroy',      via: 'delete'
  match '/users',                 to: 'sessions#users',        via: 'get'
  match '/users',                 to: 'sessions#update_users', via: 'post'
  match '/users',                 to: 'sessions#delete_users', via: 'delete'
  match '/phones',                to: 'sessions#phones',       via: 'get'
  match '/phones',                to: 'sessions#update_phones',via: 'post'
  match '/phones',                to: 'sessions#delete_phones',via: 'delete'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © Copyright 2015-<%= Time.now.year %> ICC - Site by Ivan Govnov
  </small>
  <nav>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div>
    <div class="navbar-header margin: 100">
      <a class="navbar-brand"><%= full_title(yield(:title)) %></a>
    </div>

    <ul class="nav navbar-nav pull-right">
      <% if signed_in? %>

        <li><%= link_to "Звонки", infravisor_path if current_session.infravisor or current_session.admin %></li>
        <li><%= link_to "Голосовые сообщения", voicemessages_path if current_session.infravisor or current_session.admin %></li>
	<li><%= link_to "Переадресация", callforwarder_path if current_session.callforwarder or current_session.admin %></li>
        
        <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= current_session.name %><b class="caret"></b>
          </a>
        <ul class="dropdown-menu pull-right">
        <li><%= link_to "Настройкa пользователей", users_path if current_session.admin %></li>
        <li><%= link_to "Настройкa переадресации", phones_path if current_session.admin %></li>
        <li><%= link_to "Выйти", signout_path, method: "delete" %></li>
	</ul>

      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Infra</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div id="message">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>" id="messageBox"><%= value %></div>
        <% end %>
      </div>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>